### PR TITLE
Loy task1: p-howrse-reserve-apply-affix.md

### PR DESCRIPTION
**Pull request by caimile**
## My Procedure Topic
For this project, I will use the free-to-play browser game [Howrse](https://www.howrse.com/) as the point of reference for writing my procedures. Howrse is an online horse simulation game where you can breed and sell horses, manage an equestrian center, collect in-game items, compete on teams, and participate in weekly promotional contests to earn in-game prizes.

## Completed Work

[Preview My Work](https://github.com/ENG517/Procedure/blob/loy-howrse-create-apply-affix/loyc/p-howrse-reserve-apply-affix.md)

- Created new procedure: **p-howrse-reserve-apply-affix.md**
- Procedure's goal: Create and apply an affix to a horse.

## User Scenario
Tina is 34 years old and has played various online web browser games for the past five years. Last week, she created an account on Howrse and has been trying to learn the ins and outs of  the game. She notices that some horses in the game have a piece of italicized text beneath their names that hyperlinks to a separate page displaying a bunch of horses with that same piece of italicized text tagged under their names. On this page, she notices that the piece of italicized text is called an “affix.” Tina has also started a personal project on the game where she intends to breed Fjord unicorns, and she wants to find a way to label each of the horses born from this project so that their names indicate they are a part of this specific breeding project. She realizes that an affix could be the best way to do this.

## Notable Review Requests

- How do we feel about using the gerund in the title ("Reserving and applying an affix") and a "How to _____" in the subtitles ("How to reserve an affix" "How to apply an affix to a horse")?
- The game refers to affix creation as "reserving an affix," although they do use the phrase "Create affix" in the UI at the end. I plan to use "reserve affix" as my main verbiage, but what are your thoughts on that?
- Some of the steps I listed do not begin with command verbs, but rather a location on the screen. Is this okay? What do you guys think? (Ex: "In the main menu bar, navigate..." "At the bottom of the page, select...") Should I reverse-order these sentences so that the command comes first?
- Do you think the block quotes / alerts I wrote are placed appropriately in the procedure?

### CODE REVIEW

**Comment by jckinsey01** [comment]
### Hello Caimile!

As far as what you specifically asked for advice on:
- Yes, I think the gerund in the title and the use of subtitles are the right move because I believe it lets the user know they are going to be learning both. I know sometimes I follow instructions that are set up similarly (but don't have the subsections) and I end up wondering if I did, in fact, do both things the title talked about.
- I think sticking with "reserving an affix" rather than "create an affix" if that's what the game uses most often. I would maybe specify as an alert that the may see the game refer to it as "creating" but that it means the same thing.
- I like the use of location first rather than the command verbs, because then I feel like I don't have to go back and check, I just automatically know where I'm meant to be doing what I'm doing. But I'm also coming into the program without an English B.S. so I don't know if this is some weird faux pas.
- I think the use of a quote for alerts is good, it makes sure they're distinguished from the rest of the text. I would maybe also italicize them to make them stand out more? Or bold them, but you also use bold text for the selections/actions the user is supposed to make/do, so it depends on how you feel about that consistency of style. 

## User scenario
- I like that your user scenario is based off of someone who is 34, I think that might not be an audience many people would pick (I could be wrong) and I think it's a sets a good baseline of digital literacy, if that makes sense. I think people in that demographic are generally pretty good at navigating computers, the internet, and games. It would be a way different procedure to make if you were to write that she was 60 or something.
- Maybe explain *why* an affix is the best way to complete her project. As someone who has never heard of howrse (but will probably recommend it to my horse-loving, vet student roommate) it's not immediately apparent to me *why* this helps her with her breeding program.

## Procedure
1. In your first step, I would maybe consider changing it to something like "navigate to Howrse.com and sign in to your profile" then have your current step one be step two.
2. In your prerequisites section, maybe give an example of how many affixes someone can have. Like "For example, if you have 60 days seniority, you can have two affixes" to better explain how it works. It could even be styled like an alert maybe? 
3. I would perhaps add a screen shot for steps 3 and 4, one for each or one for both, unless you think that navigation is very obvious because maybe your audience already knows what that page looks like.
4. In "How to apply an affix" in the alert/note, I would maybe just say "A horse can receive only one affix".

I think that's all I have for now, lmk if there's anything I can review before submission Tuesday!

**Comment by jckinsey01** [comment]
Hello Caimile!
As far as what you specifically asked for advice on:

Yes, I think the gerund in the title and the use of subtitles are the right move because I believe it lets the user know they are going to be learning both. I know sometimes I follow instructions that are set up similarly (but don't have the subsections) and I end up wondering if I did, in fact, do both things the title talked about.
I think sticking with "reserving an affix" rather than "create an affix" if that's what the game uses most often. I would maybe specify as an alert that the may see the game refer to it as "creating" but that it means the same thing.
I like the use of location first rather than the command verbs, because then I feel like I don't have to go back and check, I just automatically know where I'm meant to be doing what I'm doing. But I'm also coming into the program without an English B.S. so I don't know if this is some weird faux pas.
I think the use of a quote for alerts is good, it makes sure they're distinguished from the rest of the text. I would maybe also italicize them to make them stand out more? Or bold them, but you also use bold text for the selections/actions the user is supposed to make/do, so it depends on how you feel about that consistency of style.
User scenario
I like that your user scenario is based off of someone who is 34, I think that might not be an audience many people would pick (I could be wrong) and I think it's a sets a good baseline of digital literacy, if that makes sense. I think people in that demographic are generally pretty good at navigating computers, the internet, and games. It would be a way different procedure to make if you were to write that she was 60 or something.
Maybe explain why an affix is the best way to complete her project. As someone who has never heard of howrse (but will probably recommend it to my horse-loving, vet student roommate) it's not immediately apparent to me why this helps her with her breeding program.
Procedure
In your first step, I would maybe consider changing it to something like "navigate to Howrse.com and sign in to your profile" then have your current step one be step two.
In your prerequisites section, maybe give an example of how many affixes someone can have. Like "For example, if you have 60 days seniority, you can have two affixes" to better explain how it works. It could even be styled like an alert maybe?
I would perhaps add a screen shot for steps 3 and 4, one for each or one for both, unless you think that navigation is very obvious because maybe your audience already knows what that page looks like.
In "How to apply an affix" in the alert/note, I would maybe just say "A horse can receive only one affix".
I think that's all I have for now, lmk if there's anything I can review before submission Tuesday!

**Comment by jckinsey01** [comment]
Hello Caimile!
As far as what you specifically asked for advice on:

Yes, I think the gerund in the title and the use of subtitles are the right move because I believe it lets the user know they are going to be learning both. I know sometimes I follow instructions that are set up similarly (but don't have the subsections) and I end up wondering if I did, in fact, do both things the title talked about.
I think sticking with "reserving an affix" rather than "create an affix" if that's what the game uses most often. I would maybe specify as an alert that the may see the game refer to it as "creating" but that it means the same thing.
I like the use of location first rather than the command verbs, because then I feel like I don't have to go back and check, I just automatically know where I'm meant to be doing what I'm doing. But I'm also coming into the program without an English B.S. so I don't know if this is some weird faux pas.
I think the use of a quote for alerts is good, it makes sure they're distinguished from the rest of the text. I would maybe also italicize them to make them stand out more? Or bold them, but you also use bold text for the selections/actions the user is supposed to make/do, so it depends on how you feel about that consistency of style.
User scenario
I like that your user scenario is based off of someone who is 34, I think that might not be an audience many people would pick (I could be wrong) and I think it's a sets a good baseline of digital literacy, if that makes sense. I think people in that demographic are generally pretty good at navigating computers, the internet, and games. It would be a way different procedure to make if you were to write that she was 60 or something.
Maybe explain why an affix is the best way to complete her project. As someone who has never heard of howrse (but will probably recommend it to my horse-loving, vet student roommate) it's not immediately apparent to me why this helps her with her breeding program.
Procedure
In your first step, I would maybe consider changing it to something like "navigate to Howrse.com and sign in to your profile" then have your current step one be step two.
In your prerequisites section, maybe give an example of how many affixes someone can have. Like "For example, if you have 60 days seniority, you can have two affixes" to better explain how it works. It could even be styled like an alert maybe?
I would perhaps add a screen shot for steps 3 and 4, one for each or one for both, unless you think that navigation is very obvious because maybe your audience already knows what that page looks like.
In "How to apply an affix" in the alert/note, I would maybe just say "A horse can receive only one affix".
I think that's all I have for now, lmk if there's anything I can review before submission Tuesday!

**Comment by kb-boop** [comment]
## Staging

Super helpful staging. I really like how you jump right into defining the vocabulary, "affix," and give clear explanation of where to find it on the screen.

I assume your prerequisites are very clear, as someone who doesn't play this game.

## Coaching

Very solid, clear coaching. No suggestions

## Alerting

Is there anything that could go wrong for the player that you could add at the end? Are there any problems you anticipate?

**Pull request merged**
